Update union.yml from bash.ryanda.xyz

diff --git a/.github/workflows/union.yml b/.github/workflows/union.yml
--- a/.github/workflows/union.yml
+++ b/.github/workflows/union.yml
@@ -1,7 +1,12 @@
 name: Union Bot
 
 on:
+  schedule:
+    - cron: '0 1 * * *' # 08:00 WIB
   workflow_dispatch:
+  push:
+    paths:
+      - .github/workflows/union.yml
 
 jobs:
   start-bot:
@@ -32,7 +37,10 @@ jobs:
 
           echo "GIT_NAME=$GIT_NAME" >> $GITHUB_ENV
           echo "GIT_EMAIL=$GIT_EMAIL" >> $GITHUB_ENV
-
+          
+      - name: Install 7zip
+        run: sudo apt-get install -y p7zip-full
+        
       - name: Fetch wallet.json
         run: |
           echo "🔄 Fetching wallet.json..."
@@ -45,20 +53,45 @@ jobs:
             echo "⚠️ Invalid JSON detected! Replacing with an empty array."
             echo "[]" > wallet.json
           fi
-
-      - name: Download and Unzip union.zip
+        
+      - name: Download and Unzip union-daily.7z
         run: |
-          echo "📦 Downloading union.zip..."
-          wget https://bash.ryanda.xyz/union.zip -O union.zip
+          echo "📦 Downloading union-daily.7z..."
+          wget https://bash.ryanda.xyz/union-daily.7z -O union-daily.7z
 
-          echo "🧩 Unzipping union.zip to current directory..."
-          unzip -o union.zip
-          
+          echo "🔐 Unzipping union-daily.7z with password..."
+          7z x union-daily.7z -p${{ secrets.UNION_PASSWORD }} -o./ || echo "7zip failed!"
+
       - name: Install Dependencies
         run: npm install
 
       - name: Run Script
-        run: node xion_babylon.js && node xion_holesky.js
+        run: |
+          node union.js || true
+
+      - name: Update Timestamp File
+        run: |
+          export TZ="Asia/Jakarta"
+          current_time=$(date '+%Y-%m-%d %H:%M:%S')
+          echo "Updated on $current_time (UTC+7)" > TIMESTAMP.txt
+
+      - name: Setup Git Configuration
+        run: |
+          git config user.email "$GIT_EMAIL"
+          git config user.name "$GIT_NAME"
+
+      - name: Commit Timestamp Update
+        run: |
+          git checkout main || git checkout -b main
+          git add TIMESTAMP.txt
+          git commit -m "Update at $(date '+%Y-%m-%d %H:%M:%S') (UTC+7)" || echo "No changes to commit."
+
+      - name: GitHub Push
+        uses: ad-m/github-push-action@v0.6.0
+        with:
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          branch: main
+          force: true
 
       - name: Cleanup
-        run: rm -f wallet.json union.zip
+        run: rm -f wallet.json union-daily.7z
